/**
 * POST_STATUS — Trạng thái bài đăng, đồng bộ với backend enum.
 */
export const POST_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  SCHEDULED: 'SCHEDULED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  RETRYING: 'RETRYING',
  FAILED: 'FAILED',
};

/**
 * PUBLISH_MODE — Giá trị của selectedPublishId trong PostCreator UI.
 * Map sang POST_STATUS khi submit.
 */
export const PUBLISH_MODE = {
  NOW: 'now',
  SCHEDULE: 'schedule',
  REVIEW: 'review',
  DRAFT: 'draft',
};

/** Map từ PUBLISH_MODE → POST_STATUS */
export const PUBLISH_MODE_TO_STATUS = {
  [PUBLISH_MODE.NOW]: POST_STATUS.PUBLISHED,
  [PUBLISH_MODE.SCHEDULE]: POST_STATUS.SCHEDULED,
  [PUBLISH_MODE.REVIEW]: POST_STATUS.PENDING_APPROVAL,
  [PUBLISH_MODE.DRAFT]: POST_STATUS.DRAFT,
};

/** Map từ POST_STATUS → PUBLISH_MODE (để load form khi edit) */
export const STATUS_TO_PUBLISH_MODE = {
  [POST_STATUS.PUBLISHED]: PUBLISH_MODE.NOW,
  [POST_STATUS.SCHEDULED]: PUBLISH_MODE.SCHEDULE,
  [POST_STATUS.PENDING_APPROVAL]: PUBLISH_MODE.REVIEW,
  [POST_STATUS.DRAFT]: PUBLISH_MODE.DRAFT,
};
